







/// This code was generated by Basic Scaffolder.

namespace webscaffolder.Models
{
    public class VerifyCodeViewModelController
    {
		public void VerifyCodeViewModelMethod()
		{
		}
    }
}